'use client'

import { ArrowUpRight, BriefcaseBusiness, PieChart } from 'lucide-react'
import Link from 'next/link'
import { ConnectWallet } from '@/components/wallet/connect-wallet'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty'
import { Progress } from '@/components/ui/progress'
import { useVaults } from '@/hooks/use-vaults'

export default function PortfolioPage() {
  const { snapshots, connected } = useVaults()
  const positions = snapshots.filter((item) => (item.shareBalance ?? 0) > 0)
  const total = positions.reduce((sum, item) => sum + (item.shareBalance ?? 0) * (item.pricePerShare ?? 1), 0)
  if (!connected) return <div className="flex flex-col gap-8"><header><p className="text-sm font-medium text-primary">Your positions</p><h1 className="mt-2 text-4xl font-semibold">Portfolio</h1></header><Card><CardContent className="p-6"><Empty className="min-h-80"><EmptyHeader><EmptyMedia variant="icon"><BriefcaseBusiness /></EmptyMedia><EmptyTitle>Connect to view your portfolio</EmptyTitle><EmptyDescription>Your positions are read directly from Robinhood Chain.</EmptyDescription></EmptyHeader><EmptyContent><ConnectWallet /></EmptyContent></Empty></CardContent></Card></div>
  return <div className="flex flex-col gap-8"><header><p className="text-sm font-medium text-primary">Your positions</p><h1 className="mt-2 text-4xl font-semibold">Portfolio</h1><p className="mt-3 text-muted-foreground">A live view of your Robin Harvest vault shares.</p></header><section className="grid gap-4 md:grid-cols-3"><Card className="md:col-span-2"><CardHeader><CardDescription>Portfolio value</CardDescription><CardTitle className="text-4xl tabular">{total.toLocaleString(undefined, { maximumFractionDigits: 2 })} assets</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2 text-sm text-primary"><PieChart /> Across {positions.length} active {positions.length === 1 ? 'position' : 'positions'}</div></CardContent></Card><Card><CardHeader><CardDescription>Estimated annual yield</CardDescription><CardTitle className="text-3xl text-primary tabular">{positions.reduce((sum, item) => sum + ((item.shareBalance ?? 0) * (item.pricePerShare ?? 1)) * item.apy / 100, 0).toFixed(2)}</CardTitle></CardHeader></Card></section>{positions.length === 0 ? <Card><CardContent className="p-6"><Empty className="min-h-64"><EmptyHeader><EmptyMedia variant="icon"><BriefcaseBusiness /></EmptyMedia><EmptyTitle>No vault positions yet</EmptyTitle><EmptyDescription>Choose a strategy to put your assets to work.</EmptyDescription></EmptyHeader><EmptyContent><Button nativeButton={false} render={<Link href="/" />}>Explore vaults</Button></EmptyContent></Empty></CardContent></Card> : <section className="flex flex-col gap-4"><h2 className="text-2xl font-semibold">Positions</h2>{positions.map((item) => { const value = (item.shareBalance ?? 0) * (item.pricePerShare ?? 1); return <Card key={item.vault.address}><CardContent className="flex flex-col gap-5 p-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h3 className="font-semibold">{item.vault.name}</h3><Badge variant="outline">{item.vault.assetSymbol}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.shareBalance?.toLocaleString(undefined, { maximumFractionDigits: 4 })} shares</p></div><div className="w-full max-w-xs"><div className="mb-2 flex justify-between text-sm"><span className="text-muted-foreground">Allocation</span><span>{total ? ((value / total) * 100).toFixed(1) : 0}%</span></div><Progress value={total ? value / total * 100 : 0} /></div><div className="text-left md:text-right"><p className="text-lg font-semibold tabular">{value.toLocaleString(undefined, { maximumFractionDigits: 2 })} {item.vault.assetSymbol}</p><Button nativeButton={false} render={<Link href={`/vaults/${item.vault.address}`} />} variant="ghost" size="sm">Manage <ArrowUpRight data-icon="inline-end" /></Button></div></CardContent></Card>})}</section>}</div>
}
